### ISSUE TITLE
Make search box more visible

### ISSUE THREAD

**Issue by liul85** [xiaogdgenuine/Doll#1]
So I wanted to add Slack and I found that I have to scroll down a lot to find it in the app list here
<img width="585" alt="Screen Shot 2022-01-29 at 11 15 40" src="https://user-images.githubusercontent.com/1312723/151638199-fb9bbb2b-468b-4204-958f-594e3fdece77.png">

I didn't even notice that there is a search box here 🤣
<img width="602" alt="Screen Shot 2022-01-29 at 11 07 59" src="https://user-images.githubusercontent.com/1312723/151637805-0c83318a-d6a5-4191-8ba9-eb677c124933.png">

It would be good to optimize the UI and text so it's easy for user to use that search box, thanks!

**Comment by xiaogdgenuine** [comment]
Please download the version 0.0.2, a fancy searchbox is waiting for your to touch~

![image](https://user-images.githubusercontent.com/51731239/152779996-31115c01-825b-4209-a492-46e8abfb1c07.png)

**Comment by liul85** [comment]
awesome!
