### ISSUE TITLE
getting stretched icon on menu bar

### ISSUE THREAD

**Issue by liul85** [xiaogdgenuine/Doll#10]
Hi
I have two monitors, if I active the app in my left monitor, then the icon in my right monitor becomes like below
<img width="112" alt="image" src="https://user-images.githubusercontent.com/1312723/177447339-4a973837-d7c3-4801-9d32-4e013dee19ad.png">

**Comment by xiaogdgenuine** [comment]
Hi @liul85 , I refactor the icon drawing code in new version 0.0.6, and connected to 3 monitors, it seems all fine now, pls test the new version and re-open the issue if the problem persist, thanks~

https://github.com/xiaogdgenuine/Doll/releases/tag/v0.0.6

**Comment by liul85** [comment]
it works perfectly now!
