### ISSUE TITLE
Features and bug fixes proposal

### ISSUE THREAD

**Issue by diffusi-on** [xiaogdgenuine/Doll#11]
1. Can you please add an option to hide notification counter, and just show icon in menu bar
2. It is better to not show counter if there are no notications (now it shows like a dot)
3. If counter being shown like a red badge, ensure that badge width equals or higher then height (it should look like a circle if content is not too wide). It can look like an egg now, if for example number 1 or dot are displayed as badge content.

**Comment by xiaogdgenuine** [comment]
Hi @diffusi-on , to be honest I didn’t get the 2.

As I understand dot is also a notification, it’s just that the notification maybe not important for you, like a message from a slack channel.  

Do you still want me to add a option to ignore “•” badge text?

**Comment by diffusi-on** [comment]
> Hi @diffusi-on , to be honest I didn’t get the 2.
> 
> As I understand dot is also a notification, it’s just that the notification maybe not important for you, like a message from a slack channel.
> 
> Do you still want me to add a option to ignore “•” badge text?

Sorry, my mistake. This is slack specifc feature it optionaly shows ( • ) badge.

No not ignore "•", but to add settings option to disable badge and counter number on right side of icon at all and allow app to just show an icon

**Comment by xiaogdgenuine** [comment]
@diffusi-on 

Please check the v0.0.7:
https://github.com/xiaogdgenuine/Doll/releases/tag/v0.0.7

**Comment by diffusi-on** [comment]
@xiaogdgenuine yep it works. Thanks!
