### ISSUE TITLE
Unable to Add an App

### ISSUE THREAD

**Issue by xinyongjo** [xiaogdgenuine/Doll#12]
Hi, thank you for creating this tool. I find it would be really useful to keep track of the notifications. :)

I'm trying to use this on a Macbook Air M1 with macOS Big Sur v11.6. I've enabled permission but I'm still unable to add an app.

https://user-images.githubusercontent.com/49879122/179384862-31c9448f-8b4a-4873-8cd0-d93f02c1c32b.mov

**Comment by xiaogdgenuine** [comment]
That's strange, really strange, my best guess it's another bug related to how SwiftUI works on Big sur, this happens a lot actually.

Sadly I don't have a big sur Mac anymore, can't help to reproduce it, by any chance you could upgrade to latest Montery?

**Comment by xinyongjo** [comment]
It worked after I updated! Thanks 😃
