### ISSUE TITLE
Hide menu bar icon when orginal app closed

### ISSUE THREAD

**Issue by diffusi-on** [xiaogdgenuine/Doll#13]
If origonal app (e.g slack) closed, it's menu bar icon created by Doll, stays in a menu bar. I think this is incorrect and non typical for mac os behaviour. Menu bar used to show active apps status

**Comment by huikaichen** [comment]
Well some user like me may use that as a quick launch icon to open the original app...

I think most of us is using Doll to monitor apps like: Slack, Mail...I never find my self use work computer without these apps running.

It can be enhance though, I can make the icon gray to indicate it's not running.

Also I don't think an option to control `Hide icon when app is terminated` is a good one, the app just got too many options now :P.

**Comment by xiaogdgenuine** [comment]
Ok ok, next version will include this feature

**Comment by xiaogdgenuine** [comment]
Done:
https://github.com/xiaogdgenuine/Doll/releases/tag/v0.0.8
