### ISSUE TITLE
Correct typos in UI

### ISSUE THREAD

**Issue by obviousaurus** [xiaogdgenuine/Doll#14]
Just some friendly English copy-editing tips for you about these sections of the UI:

<img width="248" alt="image" src="https://user-images.githubusercontent.com/17000416/182237954-9f786d7f-4d69-48a5-a3db-71bd63206fca.png">

**Suggestion:** "Hide icons when there are no new notifications"
- _there's_ is a contraction of "there is" not "there are" but the subject is "notification**s**" so we need the plural contraction or no contraction at all
- I also pluralized "icon" because the "Hide icon when..." option applies to any app that's been added to Doll

**Suggestion:** "Show notification even when menu bar is hidden"
- _the past tense of "hide" is "hidden"_

---

<img width="250" alt="image" src="https://user-images.githubusercontent.com/17000416/182247832-4748e59b-f4ad-42b3-9305-72275137fef0.png">

**Suggestion:** 'Stop monitoring - "APPNAME"'
- Present tense uses an -ing ending

---

<img width="407" alt="image" src="https://user-images.githubusercontent.com/17000416/182248411-1f5754fd-0f86-4ed4-b143-7086e03315c7.png">

**Suggestion:** "Select an app to monitor its notifications"
- _it's_ is a contraction of "it is" and the ' is incorrect in showing possession in this context
- Doll is monitoring app notifications, not badges

**Comment by xiaogdgenuine** [comment]
@obviousaurus Thank you for bring my school experience back haha :P

Also a big sorry for people who suffering my poor english grammar, these typos will be correct in next version and your pain shall be gone.

**Comment by obviousaurus** [comment]
@xiaogdgenuine no apologies needed! I'm currently learning my 4th language, so I know all too well how hard it can be to get spelling right. English is a really frustrating language when it comes to spelling (something that many native speakers take for granted). It has so few rules and there are too many exceptions.

If you need any help copy-editing Doll, please let me know and I'll be happy to help.

**Comment by xiaogdgenuine** [comment]
New version released, all typos corrected (At least for now :P)
https://github.com/xiaogdgenuine/Doll/releases/tag/v0.0.8
