### ISSUE TITLE
Option to hide menu bar icons on a per-app basis

### ISSUE THREAD

**Issue by obviousaurus** [xiaogdgenuine/Doll#15]
Currently, hiding icons when there are no new notifications applies to all apps. It would be nice to be able to choose which apps' icons get hidden when there are no notifications by offering a set of controls in each app's dedicated window-view.

**Comment by xiaogdgenuine** [comment]
Sorry @obviousaurus , but personally I prefer the way it currently is, part of reason is that I don't have that much apps to monitored (Slack, Teams and Mail only).

However your point still stands, it just require more works in the code and more testing and I afarid I don't have much enthusiasm on this one :P... You are welcome to fork the repo and modify the app the way you want.
