### ISSUE TITLE
希望有设计师优化一下status上显示的app icon

### ISSUE THREAD

**Issue by theBillLee** [xiaogdgenuine/Doll#16]
现在都是app本身的icon和其他单色icon格格不入，希望能有一个愿意帮忙的设计师，哈哈

**Comment by xiaogdgenuine** [comment]
@theBillLee 新版本发布了，抱歉鸽了这么久～
https://github.com/xiaogdgenuine/Doll/releases/tag/v0.0.8

这个版本里你可以自己替换任意图标了，上网下载一些自定义图标就可以了，不需要什么设计师哈哈～
