### ISSUE TITLE
Bouncing red arrow? 

### ISSUE THREAD

**Issue by trzjr** [xiaogdgenuine/Doll#28]
Not sure if it's just me, but I get a giant bouncing red arrow pointing to my menu bar icons whenever a new message appears in Slack or any other app I'm monitoring with Doll. The image below is after the arrow has come to rest — but it starts by zooming in out of nowhere, on top of everything, and then it bounces in and out quite prominently for every new notification. 

<img width="279" alt="arrow" src="https://user-images.githubusercontent.com/123991948/215579326-5f0198e1-c29f-4369-8404-48b6c17db8fd.png">

I feel like the red badge and notification sound are enough? Is this something I can turn off? Apologies in advance if this is a dumb question.

**Comment by xiaogdgenuine** [comment]
Yes it can be turn off.

<img width="940" alt="image" src="https://user-images.githubusercontent.com/51731239/215775567-d1c741e3-2796-452c-acb6-2f4c8c9e7acf.png">

**Comment by trzjr** [comment]
Thank you!

**Comment by trzjr** [comment]
Just wanted to say that Doll is amazing and sorely needed on Mac. Just
donated three cups of coffee in appreciation. :-)

**Comment by xiaogdgenuine** [comment]
Oh my god thank you so much @trzjr !

I shall enjoy the coffee and you should enjoy my appreciation! :P

**Comment by stavfx** [comment]
I thought this checkbox was related to how the app is monitored or how frequently. I didn't realize that's what was causing the obnoxious arrow. Maybe worth finding a way to explain what this actually does.

And I'll take this chance to say that Doll is absolutely incredible and I recommend this tool to every mac user I know!
I used to use xbar with custom scripts that would be painful to setup and get working right (not to mention it has consistent memory leaks), then I found Doll and I've been a happy camper from day 1. Thank you!

**Comment by mikybars** [comment]
OMG! This app is pure gold and very much needed! Where can I find the donate/buy a cup of coffee action? I'm sold 💸

**Comment by mikybars** [comment]
LOL! I would've never gone there to look for in a million years 😂

**Comment by stavfx** [comment]
In fact, here https://github.com/xiaogdgenuine/Doll/pull/42 😄

**Comment by xiaogdgenuine** [comment]
> In fact, here #42 😄

OMG thank you so much @stavfx haha!

I'm glad that you guys enjoy the app :)!
