### ISSUE TITLE
Icon position seems to change, which is a problem when using apps like Hidden Bar

### ISSUE THREAD

**Issue by seemuch** [xiaogdgenuine/Doll#29]
I use [Hidden Bar](https://apps.apple.com/us/app/hidden-bar/id1452453066?mt=12), which is a free app on Mac to manage items in the menu bar. The idea is that there can be too many items in the menu bar, and not every one of the items is used on daily basis. This app helps you to hide some of the not so frequently used ones. 

When the bar is collapsed: 
<img width="589" alt="image" src="https://user-images.githubusercontent.com/2233625/222233451-2cafe65f-e049-4833-9630-839b8237e850.png">

When the bar is expanded: 
<img width="1050" alt="image" src="https://user-images.githubusercontent.com/2233625/222233499-e6ea62dc-8932-49d1-afc7-4fa8b5ebb13d.png">

I can Cmd+drag to arrange the items to manage what should be hidden.

Doll adds items to menu bar. But I noticed an issue that the icon moves. E.g. I put Slack icons in the "shown" area. But sometimes it will go to the "hidden" area by itself. 

This happened a couple of times already. I don't know how exactly this is triggered. I suspect items added by Doll removes itself and re-add itself back from time to time, for reasons I do not know. And when it does that, it will be added to the end, which is by default the hidden area.

**Comment by tspaulding0222** [comment]
Do you have either of this options selected for any icons??

![image](https://user-images.githubusercontent.com/13524501/222492629-59a85af6-3d5e-4f23-aec4-d3d652b3c727.png)

**Comment by seemuch** [comment]
Great catch. I just looked at my settings, and I had the 1st one checked and the 2nd one unchecked. 
I just unchecked both. I will observe if this fixes the issue. 
Thank you very much for pointing this out.

**Comment by seemuch** [comment]
I after unchecking both checkboxes, the problem stoped happening. Closing this issue.
