### ISSUE TITLE
Not working for Microsoft outlook

### ISSUE THREAD

**Issue by Samanm** [xiaogdgenuine/Doll#3]
This is such an awesome app and it's working as expected for Slack! But I'm not getting any notification badges/count shown for Microsoft outlook. I tried re-launching Outlook but that didn't help...

<img width="88" alt="Screen Shot 2022-03-31 at 2 28 02 PM" src="https://user-images.githubusercontent.com/863113/161152268-bbc43294-33aa-4fa0-980e-f96cdbe91bb1.png">

**Comment by Samanm** [comment]
Any updates/suggestion on this?

**Comment by xiaogdgenuine** [comment]
Hi Samanm, sorry for reply late, busy month....

Thanks for reporting, I will download Outlook and try to reproduce it, will  release a new version when it's fixed!

**Comment by Samanm** [comment]
Thank you so much @xiaogdgenuine for fixing this issue! It's working now! 🎉
