### ISSUE TITLE
Map custom icons to monitored apps

### ISSUE THREAD

**Issue by innocenzi** [xiaogdgenuine/Doll#33]
First of all, thank you for this—I've been looking for a solution to this problem for a while. 

Doll does its job very well, but I'd love to have icons that match the style of other menu bar icons.

![image](https://github.com/xiaogdgenuine/Doll/assets/16060559/96575b23-71ce-4814-a178-c87b4716c423)

Having the option to associate a custom icon to a monitored app would be super nice.

**Comment by xiaogdgenuine** [comment]
Hi @innocenzi sorry for reply late, this feature is actually implemented, a bit hard to find, you need to open Doll's setting window and hover your mouse over the app icon, then you can change it to your custom icon(Any image file supported by macOS)

<img width="780" alt="image" src="https://github.com/xiaogdgenuine/Doll/assets/51731239/de738f8b-630d-4065-bd08-c3a714d4ec60">

**Comment by innocenzi** [comment]
omg, indeed it was a bit hidden, but glad this exists! Thank you!
