### ISSUE TITLE
No count on Messages and System settings

### ISSUE THREAD

**Issue by feppos0** [xiaogdgenuine/Doll#34]
Hey! Love the app, and got it running on Ventura 13.4. I got a red badge on Apple Mail, but for Messages and System Settings I only see the icon, not the count even if I have unread messages/count on the dock. Tried remove Doll from the permissions and re-added it, but still only works for Mail.

How can I get it to work for Messages and System settings as well?

**Comment by ImanMahmoudinasab** [comment]
I marked one of my messages as unread and I see it appears as expected:
<img width="207" alt="image" src="https://github.com/xiaogdgenuine/Doll/assets/5295554/76460793-6ec6-45e2-894d-217dd1f2c014">

**Comment by feppos0** [comment]
Hi @ImanMahmoudinasab , thanks! 
I still can't get it to work, maybe the cause is that I have Swedish language instead of English on my mac? Since Messages and System settings is called "Meddelanden" and "Systeminställningar", and Mail is called the same (which works..).

**Comment by ImanMahmoudinasab** [comment]
That's my guess too. I think it uses `localName` of apps to find `mail` but since your system lang is not English it fails to find the app.

**Comment by feppos0** [comment]
@ImanMahmoudinasab thanks, yes.. Do you or perhaps @xiaogdgenuine know how to fix? Would be super useful to have this working! :)

**Comment by xiaogdgenuine** [comment]
Sorry guys for keep you wait so long, I found a solution to this problem, will release a new version by today.

**Comment by xiaogdgenuine** [comment]
@feppos0 @ImanMahmoudinasab thank you guys for reporting the issue, the latest version should solve this issue, I verified it in my own mac by switch to Swedish language:

![image](https://github.com/xiaogdgenuine/Doll/assets/51731239/76802f9e-78da-4afd-ac3f-54e4264f7213)

https://github.com/xiaogdgenuine/Doll/releases/tag/v0.0.9

Let me know if you found any new issues :)

**Comment by feppos0** [comment]
Hey @xiaogdgenuine , thank you so much for looking into this! :) 

I've uninstalled the old version completely and installed v.0.0.9 but experience the same issue..
I'm on Ventura 13.5.2 and system language in Swedish. Tried a restart of the computer after the installation. 

I tried to change the system language to English and got it working with Messages, but going back to Swedish it fails to fetch the Messages app badge.

Here's a video of how it looks like on my computer. When searching app directly in Doll, it catches "Meddelanden", but if I choose Pick - it shows "Messages" - don't know if this is relevant to the issue.

So happy you're looking into this! Thank you!


https://github.com/xiaogdgenuine/Doll/assets/56875180/482eacd9-ec2b-419f-a594-85e664975dd4

**Comment by xiaogdgenuine** [comment]
@feppos0 thank you for testing, yep I can reproduce this, it appears that macOS somehow [cache] or [fallback] to English version when Doll using 「CFBundleDisplayName」to query for the localized app's name.

I need to find a reliable way to get the localized app name like "Meddelanden" and "Systeminställningar", if I couldn't find one, a workaround would be just let you input that name haha, after all all I need is just a correct app name that is same as the one displayed in Dock bar, then everything should works.

Wait for my good or bad news, so be very soon....

**Comment by xiaogdgenuine** [comment]
Hi @feppos0 could you try this one?
https://github.com/xiaogdgenuine/Doll/releases/tag/v0.0.9.1

This time don't use the "Pick" button, just search inside doll, remove and add the app again.

**Comment by feppos0** [comment]
@xiaogdgenuine It works perfectly now!
Thanks once again!

**Comment by xiaogdgenuine** [comment]
Glad it solves the problem, to be honest I can't find a reliable way to get the localized app name if you pick the application from Finder, but should be good for now :P

**Comment by ImanMahmoudinasab** [comment]
@xiaogdgenuine well done!

**Comment by yesnt10** [comment]
same problem with Turkish :(
