### ISSUE TITLE
Proposal: pop the settings menu when the Doll app is manually opened

### ISSUE THREAD

**Issue by SokolskyNikita** [xiaogdgenuine/Doll#4]
Today I wanted to add a second app to monitor with Doll but was struggling to open the settings menu. I kept invoking Doll.app, but nothing was showing up. Finally I went to the repo and realized I have to press Option+click on the icon to get the Settings. I propose modifying the behavior so that manually opening the Doll app when its already running will open the Doll settings menu.

**Comment by xiaogdgenuine** [comment]
Propose accepted, I will add such behavior, also I will enable "Double finger tap on icon (or right click if you are using mouse)" to config settings

**Comment by xiaogdgenuine** [comment]
Hi @SokolskyNikita , new version 0.0.4 is out, please give it a try and see if it works fine in your machine, thanks!

https://github.com/xiaogdgenuine/Doll/releases/tag/v0.0.4

**Comment by SokolskyNikita** [comment]
I confirm it works!
