### ISSUE TITLE
Version number visible in app?

### ISSUE THREAD

**Issue by hoffmaan** [xiaogdgenuine/Doll#45]
Hi,

Is there a place in the app where I can check which version is currently running? If I just missed it: where is it? If not: may I suggest you add this information in the about box?

Thank you very much. Great app, great job!

Regards,
Andreas

**Comment by xiaogdgenuine** [comment]
Thanks @hoffmaan , I add the version number in the latest release :P
https://github.com/xiaogdgenuine/Doll/releases/latest
