### ISSUE TITLE
Why do I see a red arrow when I get a notification?

### ISSUE THREAD

**Issue by bonfiglioalessio** [xiaogdgenuine/Doll#46]
Hi, my name is Alessio and I am thankful that I downloaded this app. 
I have added 2 apps to have the badge in my status bar but when a notification comes, there is a big red arrow in the badge icon.

This is the screenshot. How do I remove this feature that looks like for accessibility?

<img width="1000" alt="Screenshot 2023-12-01 at 09 18 00" src="https://github.com/xiaogdgenuine/Doll/assets/52224078/582ba9a5-f16a-4e96-a5f5-d50d2e21a252">

Thanks all!

**Comment by xiaogdgenuine** [comment]
@bonfiglioalessio 
https://github.com/xiaogdgenuine/Doll/issues/28#issuecomment-1410375784

**Comment by bonfiglioalessio** [comment]
Thanks a lot!
Maybe it is better to change the text to make it clear that it is what the red arrow shows?
