### ISSUE TITLE
Black background on the icons

### ISSUE THREAD

**Issue by rakumairu** [xiaogdgenuine/Doll#49]
Just updated macos to 14.2 (23C64) and the icons now have black background for some reason, minor issue but a quite noticable at times.

![CleanShot 2023-12-17 at 14 13 09@2x](https://github.com/xiaogdgenuine/Doll/assets/29097335/127f7417-31ef-42ad-a1ff-2d4e8f33f12c)

**Comment by xiaogdgenuine** [comment]
Yeah I notice that too, must be some API behaviors changed after 14.2, I will fix it soon~

**Comment by rakumairu** [comment]
thanks! looking forward for the update!

**Comment by xiaogdgenuine** [comment]
@rakumairu It seems I can fix this by simply compile the source code with latest Xcode... :P

Anyway it's fixed, pls download the latest release:
https://github.com/xiaogdgenuine/Doll/releases/latest

**Comment by rakumairu** [comment]
@xiaogdgenuine, just saw the notification

It's fixed with the latest version, thanks for your work!
