### ISSUE TITLE
[Enhancement] Optionally display the red notification badge on the icon

### ISSUE THREAD

**Issue by Samanm** [xiaogdgenuine/Doll#5]
It would be nice to get the option to show the red notification on the icon in order to draw more attention when a new notification comes in. Similar to the existing notification badge shown on the icons in the dock.

<img width="152" alt="Screen Shot 2022-04-19 at 11 52 53 AM" src="https://user-images.githubusercontent.com/863113/164075269-f2d03764-91d2-4078-9b72-c1cc26d9d37d.png">

**Comment by rawcat** [comment]
I second that suggestion. Some kind of color highlight, background color for the number etc. would be usefull!

**Comment by xiaogdgenuine** [comment]
Here you go boys~

<img width="836" alt="image" src="https://user-images.githubusercontent.com/51731239/173211679-4202e9e9-9d48-437d-bb4a-891c81dc183b.png">

<img width="210" alt="show-as-badge" src="https://user-images.githubusercontent.com/51731239/173211667-b5dbba50-a817-4a48-9f88-233098bc974f.png">

I'm not good at UI design at all, it isn't that pretty as the system one, but I sure it will draw you some attention haha~

Latest release:
https://github.com/xiaogdgenuine/Doll/releases/tag/v0.0.5

**Comment by seahindeniz** [comment]
There's a minor issue with the badges' position. It doesn't show half of it
![image](https://user-images.githubusercontent.com/5789670/173246963-feee5b59-21ce-4ed4-8db7-fcca0a277041.png)

**Comment by huikaichen** [comment]
@seahindeniz NP~ I will fix it this week

**Comment by Samanm** [comment]
Thank you so much @xiaogdgenuine, although it didn't work for me. When I installed the above version, it no longer showed any notifications on any of the apps and basically stopped monitoring those. Although it would be nice if you could reduce the spacing between the icons (preferably back to what it was originally) as I already have other few other icons in the menubar and won't be able to fit them all with the current spacing. Thanks!

**Comment by huikaichen** [comment]
@Samanm Forget to mention, everytime you re-install the app that require `Accessibility permission`, you need to re-add that app into "Security > Privacy > Accessibility" panel.

This icon will show if the app don't got the Accessibility permission:
![image](https://user-images.githubusercontent.com/100546065/173719595-6f7c0409-ab02-4b72-86fd-309bbb472384.png)

Click on it and open the system preference to add the app again, that should work.

**Comment by xiaogdgenuine** [comment]
Hi guys, new version 0.0.6 should resolve the half badge display issue, along with couple of other fixes, pls enjoy and let me know if anything isn't working properly~

https://github.com/xiaogdgenuine/Doll/releases/tag/v0.0.6
