### ISSUE TITLE
[Enhancement] Option to hide apps with no new notifications

### ISSUE THREAD

**Issue by marvinkurock** [xiaogdgenuine/Doll#6]
I like the app, I was looking for exactly this.
The only suggestion I have would be to hide apps with no notifications (0).
If thats possible I would really appreciate it.

Great work - thanks

**Comment by huikaichen** [comment]
That's a really good point, I like this, I will work on it this weekend!

**Comment by xiaogdgenuine** [comment]
Here you go @marvinkurock 

https://github.com/xiaogdgenuine/Doll/releases/tag/v0.0.5
