### ISSUE TITLE
Can't list apps

### ISSUE THREAD

**Issue by seahindeniz** [xiaogdgenuine/Doll#7]
Hi,
I just download the app and seems like it doesn't work properly. I have tried searching apps, or waiting my apps to get listed, or anything that would let me select an app or indicates something similar.
I have tried manually giving the accessibility permission from the privacy settings, but it didn't work.

![image](https://user-images.githubusercontent.com/5789670/173156239-1e233162-a862-480f-8c9d-67fe71c264aa.png)

**Comment by xiaogdgenuine** [comment]
That's strange, no just the list isn't showing, the Search icon is displayed as "?" mark as well.

No thing I did is special here, I create a `NSMetadataQuery` to ask system return items with `kMDItemContentType == "com.apple.application-bundle"`, which is all application bundle in your system.

My guessing is there are some wired bug in older macOS, my is 12.2, let me know yours.

You could try run this in your terminal, see if it successfully list all your application bundles:
`mdfind 'kMDItemContentType == "com.apple.application-bundle"'`

If the command is return empty, that means something wrong with your system's config, maybe Spotlight isn't turn on for meta query? But where to turn that on hahah...

**Comment by seahindeniz** [comment]
Hi, sorry for the missing details about my Mac

> In a nutshell, following commands fixed the indexing issue
> ```
> sudo mdutil -i on /
> sudo mdutil -Ea /
> sudo mdutil -a -i off
> sudo mdutil -a -i on
> ```

---

I'm using MacOS 12.4 (21F79)

Here's the output
<img width="568" alt="image" src="https://user-images.githubusercontent.com/5789670/173228552-86530671-97d7-40a8-b2af-06b13c20d77f.png">

As your suggestion, I have search about Spotlight issues and found that my Spotlight indexing service was disabled.

```bash
➜  ~ mdutil -E /
/:
2022-06-12 13:20:35.099 mdutil[4535:67508] mdutil disabling Spotlight: / -> kMDConfigSearchLevelFSSearchOnly
Error: unable to perform operation.  Try as root.  (-1)
	Indexing disabled.
```

I have then followed the instructions in this answer https://apple.stackexchange.com/a/147841/453757
and now the indexing service is working (I guess).

Here's the screenshot.
This time, I had issues with non-Apple applications, they didn't appear on the Spotlight search as well.
![image](https://user-images.githubusercontent.com/5789670/173228936-a24a916d-b774-4104-8b81-3355e185462b.png)

So I searched for a solution again and ran the following commands
```bash
sudo mdutil -a -i off
sudo mdutil -a -i on
```
Here's the output
<img width="911" alt="image" src="https://user-images.githubusercontent.com/5789670/173229172-76d0eb82-2360-40d9-a0d9-0e7faef7d9ed.png">

And now, Doll can show apps!
<img width="801" alt="image" src="https://user-images.githubusercontent.com/5789670/173229191-7565c4a1-e264-4645-a013-dfdd62a1a28b.png">

**Comment by seahindeniz** [comment]
@xiaogdgenuine, a small feedback/suggestion; you can create a troubleshooting section in the README file and maybe add the commands that would solve the 'apps doesn't show' issue.

Or, maybe you can find another approach to list applications that doesn't depend on Spotlight's indexing service 💯

**Comment by huikaichen** [comment]
Excellent @seahindeniz !!!! Thank you for sharing your findings! I will create a troubleshooting section for this!

Yeah, actually all I need for monitoring is just app's name & it's bundle identifier like "com.apple.activity-monitor"

- name is for polling & filtering notification update from `Dock`
- bundle identifier is required to get the app's icon

Name is easy to input, bundle identifier... that would require some steps, so I say, let's use Spotlight then user won't have to do that much haha~

I guess the best way would be another "Pick app" button alongside with search bar, you can click on it, pick the app you want to monitor from file picker, and I will do the rest(Read name, bundle identifier, setup monitor etc....)

You got it, wait for me~
![image](https://user-images.githubusercontent.com/100546065/173259166-481011ae-294a-40ad-ac49-6f3e50c59814.png)

**Comment by huikaichen** [comment]
By the way, I still wondering  why the search icon is showing as a question mark on your side...

Mine is fine:
<img width="836" alt="image" src="https://user-images.githubusercontent.com/100546065/173259414-241ffc41-2b52-4b7e-9ce0-41d4f7de8b70.png">

It's come from SF symbols, and that's a system embed icon library...
I upgrade my system to 12.4 yesterday, so we should have same result...
