### ISSUE TITLE
“Doll” can’t be opened because Apple cannot check it for malicious software

### ISSUE THREAD

**Issue by alexraju91** [xiaogdgenuine/Doll#9]
<img width="328" alt="Screen Shot 2022-06-20 at 4 21 36 PM" src="https://user-images.githubusercontent.com/11927055/174672942-8051964f-7e48-4cd9-9e31-7759e259ed9a.png">

**Comment by tspaulding0222** [comment]
Right click and click open to get around this for now

**Comment by xiaogdgenuine** [comment]
Sorry guys, I forgot to notarize the last release, so this warning is showing, the new version is out, should be able to open without problem, let me know if it persist and I will re-open the issue, thanks.

https://github.com/xiaogdgenuine/Doll/releases/tag/v0.0.6
